### ISSUE TITLE
prioritizing home page

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#12]
i made the mainstage shows "priority 1" to see how they would display on home page but it didn't seem to refresh

**Comment by andrewfn** [comment]
I have just updated the test site from the main site.
Have a look at: http://test.torontojazz.com/

**Comment by brianblain** [comment]
still not displaying the prioritized shows - tried clearing my cache  (3 of the shows displaying are from March - maybe you've got those boxes hard-wired?)

**Comment by andrewfn** [comment]
If you're logged into the test site, you can see them all on the front page. Very odd but I'm onto it.

**Comment by andrewfn** [comment]
I fixed it by forcing the server cache to reload. (Logged in users always see the live version, not the cached).
It should do this itself every hour, but obviously was not.
Ah, I solved it. The test site was only set to refresh every 3 hours.  I have updated it to be an average of 1/2 hour.

**Comment by brianblain** [comment]
still shows those three march events...just checked to see if they are priority 1, but not...now I have set them to "unpublished" so we'll see if that makes them go away

**Comment by andrewfn** [comment]
The answer is very simple.
You have only selected 9 headline shows, yet there are 12 spaces on the front page.
Once it has used up all the headlines, it starts again with the lowest date. (Maybe we should block it from showing any concerts on the front page that are in the past)
The simple answer is not to unpublish the old concerts (which will break any blog links to them) but to add more headline shows.

**Comment by brianblain** [comment]
will do

**Comment by brianblain** [comment]
I added a bunch more priority 1 shows but those damn March events are still showing up.  Looks like the test site is not refreshing ( I added several pics last night but not seeing them)

Pat has summoned me for 12:30 to go over things

**Comment by andrewfn** [comment]
I have to refresh the test site manually, since it requires a number of steps and passwords.
I have just done it, and will try and do it every hour today, but let me know if you need it done at a particular time.

I am focusing on dressing up the calendar page right now.
b.t.w. if an issue is closed, and you comment on it, you should press the "comment and reopen" button so that it becomes visible again. Otherwise I might easily miss it.

**Comment by andrewfn** [comment]
Anything you need done urgently (e.g. for your 12:30 meeting), add the urgent label to it using the labels tool to the right of the issue.

**Comment by brianblain** [comment]
please refresh again and see if we can make those march events go away

**Comment by brianblain** [comment]
new news items not showing up on mobile  (also Pat wanted to reduce the size of the header on mobile site)  more in a moment

**Comment by andrewfn** [comment]
The March events went away on the previous refresh. I'm going to refresh again at 11:30
I started separate issues for the other two items you mentioned otherwise they will get lost.
